package com.jiayaxing.web.model;

import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.uuid
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_uuid
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String userUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_name
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_sex
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_birthday
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_birthday_time
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String userBirthdayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_type
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_name
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String orderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_detail_id
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private Integer orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_detail_name
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String orderDetailName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_detail_status
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String orderDetailStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.question
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.notes
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.update_time
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.uuid
     *
     * @return the value of order_info.uuid
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.uuid
     *
     * @param uuid the value for order_info.uuid
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_uuid
     *
     * @return the value of order_info.user_uuid
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_uuid
     *
     * @param userUuid the value for order_info.user_uuid
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_name
     *
     * @return the value of order_info.user_name
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_name
     *
     * @param userName the value for order_info.user_name
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_sex
     *
     * @return the value of order_info.user_sex
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_sex
     *
     * @param userSex the value for order_info.user_sex
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_birthday
     *
     * @return the value of order_info.user_birthday
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_birthday
     *
     * @param userBirthday the value for order_info.user_birthday
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_birthday_time
     *
     * @return the value of order_info.user_birthday_time
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getUserBirthdayTime() {
        return userBirthdayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_birthday_time
     *
     * @param userBirthdayTime the value for order_info.user_birthday_time
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setUserBirthdayTime(String userBirthdayTime) {
        this.userBirthdayTime = userBirthdayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_type
     *
     * @return the value of order_info.order_type
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_type
     *
     * @param orderType the value for order_info.order_type
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_name
     *
     * @return the value of order_info.order_name
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_name
     *
     * @param orderName the value for order_info.order_name
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_detail_id
     *
     * @return the value of order_info.order_detail_id
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public Integer getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_detail_id
     *
     * @param orderDetailId the value for order_info.order_detail_id
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_detail_name
     *
     * @return the value of order_info.order_detail_name
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getOrderDetailName() {
        return orderDetailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_detail_name
     *
     * @param orderDetailName the value for order_info.order_detail_name
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setOrderDetailName(String orderDetailName) {
        this.orderDetailName = orderDetailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_detail_status
     *
     * @return the value of order_info.order_detail_status
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getOrderDetailStatus() {
        return orderDetailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_detail_status
     *
     * @param orderDetailStatus the value for order_info.order_detail_status
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setOrderDetailStatus(String orderDetailStatus) {
        this.orderDetailStatus = orderDetailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.question
     *
     * @return the value of order_info.question
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.question
     *
     * @param question the value for order_info.question
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.notes
     *
     * @return the value of order_info.notes
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.notes
     *
     * @param notes the value for order_info.notes
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.update_time
     *
     * @return the value of order_info.update_time
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.update_time
     *
     * @param updateTime the value for order_info.update_time
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}