package com.jiayaxing.web.model;

public class ShiroUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_user.id
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_user.user_name
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_user.password
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_user.locked
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	private Byte locked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_user.deleted
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	private Byte deleted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_user.id
	 * @return  the value of shiro_user.id
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_user.id
	 * @param id  the value for shiro_user.id
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_user.user_name
	 * @return  the value of shiro_user.user_name
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_user.user_name
	 * @param userName  the value for shiro_user.user_name
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_user.password
	 * @return  the value of shiro_user.password
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_user.password
	 * @param password  the value for shiro_user.password
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_user.locked
	 * @return  the value of shiro_user.locked
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public Byte getLocked() {
		return locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_user.locked
	 * @param locked  the value for shiro_user.locked
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public void setLocked(Byte locked) {
		this.locked = locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_user.deleted
	 * @return  the value of shiro_user.deleted
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public Byte getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_user.deleted
	 * @param deleted  the value for shiro_user.deleted
	 * @mbg.generated  Thu Jul 19 10:21:57 CST 2018
	 */
	public void setDeleted(Byte deleted) {
		this.deleted = deleted;
	}
}