package com.jiayaxing.web.model;

public class ShiroRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_role.id
	 * @mbg.generated  Wed Jun 13 09:29:13 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_role.name
	 * @mbg.generated  Wed Jun 13 09:29:13 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_role.role
	 * @mbg.generated  Wed Jun 13 09:29:13 CST 2018
	 */
	private String role;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_role.id
	 * @return  the value of shiro_role.id
	 * @mbg.generated  Wed Jun 13 09:29:13 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_role.id
	 * @param id  the value for shiro_role.id
	 * @mbg.generated  Wed Jun 13 09:29:13 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_role.name
	 * @return  the value of shiro_role.name
	 * @mbg.generated  Wed Jun 13 09:29:13 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_role.name
	 * @param name  the value for shiro_role.name
	 * @mbg.generated  Wed Jun 13 09:29:13 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_role.role
	 * @return  the value of shiro_role.role
	 * @mbg.generated  Wed Jun 13 09:29:13 CST 2018
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_role.role
	 * @param role  the value for shiro_role.role
	 * @mbg.generated  Wed Jun 13 09:29:13 CST 2018
	 */
	public void setRole(String role) {
		this.role = role;
	}
}