package com.jiayaxing.web.model;

public class ShiroRolePermissonKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_role_permisson.id
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_role_permisson.role_id
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_role_permisson.perm_id
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	private Integer permId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_role_permisson.id
	 * @return  the value of shiro_role_permisson.id
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_role_permisson.id
	 * @param id  the value for shiro_role_permisson.id
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_role_permisson.role_id
	 * @return  the value of shiro_role_permisson.role_id
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_role_permisson.role_id
	 * @param roleId  the value for shiro_role_permisson.role_id
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_role_permisson.perm_id
	 * @return  the value of shiro_role_permisson.perm_id
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public Integer getPermId() {
		return permId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_role_permisson.perm_id
	 * @param permId  the value for shiro_role_permisson.perm_id
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public void setPermId(Integer permId) {
		this.permId = permId;
	}
}