package com.jiayaxing.web.model;

public class ShiroRolePermisson extends ShiroRolePermissonKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_role_permisson.role_name
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_role_permisson.perm_name
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	private String permName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_role_permisson.perm_perm
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	private String permPerm;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_role_permisson.role_name
	 * @return  the value of shiro_role_permisson.role_name
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_role_permisson.role_name
	 * @param roleName  the value for shiro_role_permisson.role_name
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_role_permisson.perm_name
	 * @return  the value of shiro_role_permisson.perm_name
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public String getPermName() {
		return permName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_role_permisson.perm_name
	 * @param permName  the value for shiro_role_permisson.perm_name
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public void setPermName(String permName) {
		this.permName = permName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_role_permisson.perm_perm
	 * @return  the value of shiro_role_permisson.perm_perm
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public String getPermPerm() {
		return permPerm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_role_permisson.perm_perm
	 * @param permPerm  the value for shiro_role_permisson.perm_perm
	 * @mbg.generated  Wed Jun 13 09:31:19 CST 2018
	 */
	public void setPermPerm(String permPerm) {
		this.permPerm = permPerm;
	}
}