package com.jiayaxing.web.model;

public class ShiroUserRole extends ShiroUserRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_user_role.user_name
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_user_role.role_name
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiro_user_role.role_role
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	private String roleRole;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_user_role.user_name
	 * @return  the value of shiro_user_role.user_name
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_user_role.user_name
	 * @param userName  the value for shiro_user_role.user_name
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_user_role.role_name
	 * @return  the value of shiro_user_role.role_name
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_user_role.role_name
	 * @param roleName  the value for shiro_user_role.role_name
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiro_user_role.role_role
	 * @return  the value of shiro_user_role.role_role
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	public String getRoleRole() {
		return roleRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiro_user_role.role_role
	 * @param roleRole  the value for shiro_user_role.role_role
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	public void setRoleRole(String roleRole) {
		this.roleRole = roleRole;
	}
}