package com.jiayaxing.web.model;

import java.util.Date;

public class Test01 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.id
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.uuid
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.password
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.mobile
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.email
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.name
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.sex
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.solarOrLunar
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String solarorlunar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.birthday
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.birthdayTime
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String birthdaytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.adressProvince
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String adressprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.adressCity
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String adresscity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.adressCounty
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private String adresscounty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.update_time
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.create_time
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.id
     *
     * @return the value of test01.id
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.id
     *
     * @param id the value for test01.id
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.uuid
     *
     * @return the value of test01.uuid
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.uuid
     *
     * @param uuid the value for test01.uuid
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.password
     *
     * @return the value of test01.password
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.password
     *
     * @param password the value for test01.password
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.mobile
     *
     * @return the value of test01.mobile
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.mobile
     *
     * @param mobile the value for test01.mobile
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.email
     *
     * @return the value of test01.email
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.email
     *
     * @param email the value for test01.email
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.name
     *
     * @return the value of test01.name
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.name
     *
     * @param name the value for test01.name
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.sex
     *
     * @return the value of test01.sex
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.sex
     *
     * @param sex the value for test01.sex
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.solarOrLunar
     *
     * @return the value of test01.solarOrLunar
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getSolarorlunar() {
        return solarorlunar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.solarOrLunar
     *
     * @param solarorlunar the value for test01.solarOrLunar
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setSolarorlunar(String solarorlunar) {
        this.solarorlunar = solarorlunar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.birthday
     *
     * @return the value of test01.birthday
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.birthday
     *
     * @param birthday the value for test01.birthday
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.birthdayTime
     *
     * @return the value of test01.birthdayTime
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getBirthdaytime() {
        return birthdaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.birthdayTime
     *
     * @param birthdaytime the value for test01.birthdayTime
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setBirthdaytime(String birthdaytime) {
        this.birthdaytime = birthdaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.adressProvince
     *
     * @return the value of test01.adressProvince
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getAdressprovince() {
        return adressprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.adressProvince
     *
     * @param adressprovince the value for test01.adressProvince
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setAdressprovince(String adressprovince) {
        this.adressprovince = adressprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.adressCity
     *
     * @return the value of test01.adressCity
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getAdresscity() {
        return adresscity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.adressCity
     *
     * @param adresscity the value for test01.adressCity
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setAdresscity(String adresscity) {
        this.adresscity = adresscity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.adressCounty
     *
     * @return the value of test01.adressCounty
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public String getAdresscounty() {
        return adresscounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.adressCounty
     *
     * @param adresscounty the value for test01.adressCounty
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setAdresscounty(String adresscounty) {
        this.adresscounty = adresscounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.update_time
     *
     * @return the value of test01.update_time
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.update_time
     *
     * @param updateTime the value for test01.update_time
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.create_time
     *
     * @return the value of test01.create_time
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.create_time
     *
     * @param createTime the value for test01.create_time
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}