package com.jiayaxing.web.dao;

import java.util.List;
import java.util.Map;

import com.jiayaxing.web.model.OrderInfo;

public interface OrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    int insert(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    int insertSelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    OrderInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    int updateByPrimaryKeySelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Aug 26 14:07:34 CST 2018
     */
    int updateByPrimaryKey(OrderInfo record);
    
    List<Map<String, Object>> getOrderList(Map<String, Object> map);
    
    int getOrderListTotalSize(Map<String, Object> map);
}