package com.jiayaxing.web.dao;

import java.util.Map;

import com.jiayaxing.web.model.ShiroUser;

public interface ShiroUserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user
	 * @mbg.generated  Wed Jun 13 09:31:47 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user
	 * @mbg.generated  Wed Jun 13 09:31:47 CST 2018
	 */
	int insert(ShiroUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user
	 * @mbg.generated  Wed Jun 13 09:31:47 CST 2018
	 */
	int insertSelective(ShiroUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user
	 * @mbg.generated  Wed Jun 13 09:31:47 CST 2018
	 */
	ShiroUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user
	 * @mbg.generated  Wed Jun 13 09:31:47 CST 2018
	 */
	int updateByPrimaryKeySelective(ShiroUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user
	 * @mbg.generated  Wed Jun 13 09:31:47 CST 2018
	 */
	int updateByPrimaryKey(ShiroUser record);

	Map<String,Object> getUserInfoByUsername(String name);
	
	Map<String,Object> getUserInfo(Integer id);
}