package com.jiayaxing.web.dao;

import com.jiayaxing.web.model.ShiroPermission;

public interface ShiroPermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_permission
	 * @mbg.generated  Wed Jun 13 09:30:47 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_permission
	 * @mbg.generated  Wed Jun 13 09:30:47 CST 2018
	 */
	int insert(ShiroPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_permission
	 * @mbg.generated  Wed Jun 13 09:30:47 CST 2018
	 */
	int insertSelective(ShiroPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_permission
	 * @mbg.generated  Wed Jun 13 09:30:47 CST 2018
	 */
	ShiroPermission selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_permission
	 * @mbg.generated  Wed Jun 13 09:30:47 CST 2018
	 */
	int updateByPrimaryKeySelective(ShiroPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_permission
	 * @mbg.generated  Wed Jun 13 09:30:47 CST 2018
	 */
	int updateByPrimaryKey(ShiroPermission record);
}