package com.jiayaxing.web.dao;

import java.util.Set;

import com.jiayaxing.web.model.ShiroUserRole;
import com.jiayaxing.web.model.ShiroUserRoleKey;

public interface ShiroUserRoleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user_role
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	int deleteByPrimaryKey(ShiroUserRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user_role
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	int insert(ShiroUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user_role
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	int insertSelective(ShiroUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user_role
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	ShiroUserRole selectByPrimaryKey(ShiroUserRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user_role
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	int updateByPrimaryKeySelective(ShiroUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shiro_user_role
	 * @mbg.generated  Wed Jun 13 09:32:14 CST 2018
	 */
	int updateByPrimaryKey(ShiroUserRole record);

	Set<String> getRolesByUsername(String name);
}