package com.jiayaxing.web.dao;

import com.jiayaxing.web.model.Test01;

public interface Test01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    int insert(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    int insertSelective(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    Test01 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    int updateByPrimaryKeySelective(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Tue Jun 05 13:43:31 CST 2018
     */
    int updateByPrimaryKey(Test01 record);
}